# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

builds:
  - binary: talki

    ldflags:
      - -H=windowsgui

archives:
  - id: talki

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE.md
      - CHANGELOG.md

changelog:
  disable: true

release:
  mode: "keep-existing"
