# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

builds:
  - binary: talki

    goos:
      - windows
      - linux

    ldflags:
      - -s -w
      - >-
        {{- if eq .Os "windows" }}
          -H windowsgui
        {{- end }}

archives:
  - id: talki

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE.md
      - CHANGELOG.md

changelog:
  disable: true

release:
  mode: "keep-existing"
